---
# tasks file for dev-work

  - name: Get current OSP-related Bash env vars
    shell: "env | grep OS_"
    register: osp_vars
    changed_when: false

  - name: Print current OSP-related Bash env vars (for debugging, if required)
    debug:
      var: osp_vars.stdout_lines
    changed_when: false

  - name: Ensuring authentication can occur with current OSP-related Bash env vars
    os_auth:
      auth_type: password
    changed_when: false

  - name: install all the dev rpms
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ dev_work.rpms }}"


  - name: install the pip dev
    pip:
      name: "{{ item.1 }}"
      virtualenv: "{{ item.0.path }}"
      state: latest
    with_subelements: 
      - "{{ dev_work.virtualenvs }}"
      - packages 

  - name: install the gems for dev
    gem:
      name: "{{ item }}"
      state: latest
    with_items: "{{ dev_work.gem }}"
